### ISSUE TITLE
hovmoller plot example

### ISSUE THREAD

**Issue by carbonmetrics** [oscarperpinan/rastervis#63] opened 2021-03-10 06:21 UTC
I copy/paste from help rasterVis::hovmoller in a vanilla R session:

```
library(rasterVis)

old <- setwd(tempdir())
download.file('https://raw.github.com/oscarperpinan/spacetime-vis/master/data/SISmm2008_CMSAF.zip',
              'SISmm2008_CMSAF.zip', method='wget')
unzip('SISmm2008_CMSAF.zip')

listFich <- dir(pattern='\\.nc')
stackSIS <- stack(listFich)
stackSIS <- stackSIS*24 ##from irradiance (W/m2) to irradiation Wh/m2

idx <- seq(as.Date('2008-01-15'), as.Date('2008-12-15'), 'month')

SISmm <- setZ(stackSIS, idx)
names(SISmm) <- month.abb

## Latitude as default
hovmoller(SISmm, xlab='Latitude')
```
This fails:
```
> stackSIS <- stack(listFich)
Error in as.Date(time, origin = startDate) : object 'startDate' not found
Error in as.Date(time, origin = startDate) : object 'startDate' not found
Error in as.Date(time, origin = startDate) : object 'startDate' not found
Error in as.Date(time, origin = startDate) : object 'startDate' not found
Error in as.Date(time, origin = startDate) : object 'startDate' not found
Error in as.Date(time, origin = startDate) : object 'startDate' not found
Error in as.Date(time, origin = startDate) : object 'startDate' not found
Error in as.Date(time, origin = startDate) : object 'startDate' not found
Error in as.Date(time, origin = startDate) : object 'startDate' not found
Error in as.Date(time, origin = startDate) : object 'startDate' not found
Error in as.Date(time, origin = startDate) : object 'startDate' not found
Error in as.Date(time, origin = startDate) : object 'startDate' not found
Error in as.Date(time, origin = startDate) : object 'startDate' not found
```
What gives?

**Comment by rhijmans** [comment] 2021-03-10 07:13
I cannot reproduce the error ---- works fine for me on windows and ubuntu

**Comment by carbonmetrics** [comment] 2021-03-10 08:18
```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=nl_NL.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=nl_NL.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=nl_NL.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rasterVis_0.47      latticeExtra_0.6-29 lattice_0.20-41     raster_3.3-7        sp_1.4-2           

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5         codetools_0.2-16   png_0.1-7          viridisLite_0.3.0  zoo_1.8-8          grid_3.6.3        
 [7] ncdf4_1.17         hexbin_1.28.0      rgdal_1.5-12       RColorBrewer_1.1-2 tools_3.6.3        jpeg_0.1-8.1      
[13] parallel_3.6.3     compiler_3.6.3    
```

**Comment by oscarperpinan** [comment] 2021-03-13 17:12
I am not sure if that is the cause, but your R version is 1 year old. You should update R and the packages.

**Comment by alequech** [comment] 2021-03-20 22:50
I am having trouble using hovmoller with my data, just like with the example.    

The example... 
```
library(rasterVis)

old <- setwd(tempdir())
download.file('https://raw.github.com/oscarperpinan/spacetime-vis/master/data/SISmm2008_CMSAF.zip',
              'SISmm2008_CMSAF.zip', method='wget')
unzip('SISmm2008_CMSAF.zip')

listFich <- dir(pattern='\\.nc')
stackSIS <- stack(listFich)
stackSIS <- stackSIS*24 ##from irradiance (W/m2) to irradiation Wh/m2

idx <- seq(as.Date('2008-01-15'), as.Date('2008-12-15'), 'month')

SISmm <- setZ(stackSIS, idx)
names(SISmm) <- month.abb

## Latitude as default
hovmoller(SISmm, xlab='Latitude')
```
This is the error I get
```
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘zonal’ for signature ‘"RasterBrick", "numeric"’
```
Finally my sessionInfo 
```
R version 4.0.4 (2021-02-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Pop!_OS 20.04 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=es_MX.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=es_MX.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=es_MX.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=es_MX.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rasterVis_0.50      latticeExtra_0.6-29 lattice_0.20-41     terra_1.1-4         raster_3.4-5        sp_1.4-5           

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6         codetools_0.2-18   png_0.1-7          viridisLite_0.3.0  zoo_1.8-8          grid_4.0.4         ncdf4_1.17        
 [8] hexbin_1.28.2      rgdal_1.5-23       RColorBrewer_1.1-2 tools_4.0.4        jpeg_0.1-8.1       yaml_2.2.1         parallel_4.0.4    
[15] compiler_4.0.4 
```
I tried installing version 0.45, but the error persists.

**Comment by oscarperpinan** [comment] 2021-03-21 09:37
My fault. I have found the bug. It will be fixed in the next commit.

**Closed** 2021-03-21 09:38 UTC
